### ISSUE TITLE
Parameter and information tracking

### ISSUE THREAD

**Issue by ByteOfKathy** [C2H2-UF/ScheduGator#13]
- [x] Implement tracking of classes added/removed
- [x] Implement tracking of blocked time slots
- [x] Implement tracking of additional (to be displayed) schedule details
